### ISSUE TITLE
Modified keys do not trigger clickety clacks.

### ISSUE THREAD

**Issue by MurphyMarkW** [millerjs/modelm#3]
Did not check master branch, only the differentiate-keys branch. It seems that modifier keys do not trigger a clack. Examples include:
- shift
- alt / opt
- command
- ctrl
- fn
- capslock
- fn + function keys

It would be nice if these would register clacks just like other keys. Is this a limitation of the OS X event handling system, or just needing implementation on the modelm side?

**Comment by millerjs** [comment]
Nope, this was actually a [design choice](https://github.com/millerjs/modelm/blob/master/src/keyboard.rs#L203) to ignore `FlagsChanged` because I personally am changing Control every key stroke or so and figured I'd find it annoying.

I'll treat this issue as a feature request to enable it.
